# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configGui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2 EXCEPT: translateTR() function.
#
# WARNING! All changes made in this file will be lost! If you recompile this file using the "*.ui" file


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_configWindow(object):
    def setupUi(self, configWindow):
        configWindow.setObjectName("configWindow")
        configWindow.resize(942, 658)
        font = QtGui.QFont()
        font.setPointSize(12)
        configWindow.setFont(font)
        configWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(configWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBoxPageNumber = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxPageNumber.setFont(font)
        self.groupBoxPageNumber.setObjectName("groupBoxPageNumber")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxPageNumber)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.groupBoxNumberingMethod = QtWidgets.QGroupBox(self.groupBoxPageNumber)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxNumberingMethod.setFont(font)
        self.groupBoxNumberingMethod.setObjectName("groupBoxNumberingMethod")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBoxNumberingMethod)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioFil = QtWidgets.QRadioButton(self.groupBoxNumberingMethod)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioFil.setFont(font)
        self.radioFil.setCheckable(True)
        self.radioFil.setChecked(False)
        self.radioFil.setObjectName("radioFil")
        self.verticalLayout_2.addWidget(self.radioFil)
        self.radioNumb = QtWidgets.QRadioButton(self.groupBoxNumberingMethod)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioNumb.setFont(font)
        self.radioNumb.setCheckable(True)
        self.radioNumb.setChecked(False)
        self.radioNumb.setObjectName("radioNumb")
        self.verticalLayout_2.addWidget(self.radioNumb)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addWidget(self.groupBoxNumberingMethod)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.groupBoxForeColor = QtWidgets.QGroupBox(self.groupBoxPageNumber)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxForeColor.setFont(font)
        self.groupBoxForeColor.setObjectName("groupBoxForeColor")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBoxForeColor)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblPnumFore = QtWidgets.QLabel(self.groupBoxForeColor)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lblPnumFore.setFont(font)
        self.lblPnumFore.setObjectName("lblPnumFore")
        self.verticalLayout_4.addWidget(self.lblPnumFore)
        self.btnChgPNumFore = QtWidgets.QPushButton(self.groupBoxForeColor)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnChgPNumFore.setFont(font)
        self.btnChgPNumFore.setObjectName("btnChgPNumFore")
        self.verticalLayout_4.addWidget(self.btnChgPNumFore)
        self.verticalLayout_3.addWidget(self.groupBoxForeColor)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.checkBoxPnumAddBG = QtWidgets.QCheckBox(self.groupBoxPageNumber)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxPnumAddBG.setFont(font)
        self.checkBoxPnumAddBG.setChecked(False)
        self.checkBoxPnumAddBG.setObjectName("checkBoxPnumAddBG")
        self.verticalLayout_3.addWidget(self.checkBoxPnumAddBG)
        self.groupBoxBckColor = QtWidgets.QGroupBox(self.groupBoxPageNumber)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxBckColor.setFont(font)
        self.groupBoxBckColor.setObjectName("groupBoxBckColor")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBoxBckColor)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lblPnumBack = QtWidgets.QLabel(self.groupBoxBckColor)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lblPnumBack.setFont(font)
        self.lblPnumBack.setObjectName("lblPnumBack")
        self.verticalLayout_9.addWidget(self.lblPnumBack)
        self.btnChgNumBack = QtWidgets.QPushButton(self.groupBoxBckColor)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnChgNumBack.setFont(font)
        self.btnChgNumBack.setObjectName("btnChgNumBack")
        self.verticalLayout_9.addWidget(self.btnChgNumBack)
        self.verticalLayout_3.addWidget(self.groupBoxBckColor)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblFontSize1 = QtWidgets.QLabel(self.groupBoxPageNumber)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblFontSize1.setFont(font)
        self.lblFontSize1.setObjectName("lblFontSize1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblFontSize1)
        self.spinBoxPNumFontSize = QtWidgets.QSpinBox(self.groupBoxPageNumber)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBoxPNumFontSize.setFont(font)
        self.spinBoxPNumFontSize.setMaximum(999999999)
        self.spinBoxPNumFontSize.setProperty("value", 30)
        self.spinBoxPNumFontSize.setObjectName("spinBoxPNumFontSize")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBoxPNumFontSize)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblPosition = QtWidgets.QLabel(self.groupBoxPageNumber)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblPosition.setFont(font)
        self.lblPosition.setObjectName("lblPosition")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblPosition)
        self.comboBoxPnumPos = QtWidgets.QComboBox(self.groupBoxPageNumber)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxPnumPos.setFont(font)
        self.comboBoxPnumPos.setObjectName("comboBoxPnumPos")
        self.comboBoxPnumPos.addItem("")
        self.comboBoxPnumPos.addItem("")
        self.comboBoxPnumPos.addItem("")
        self.comboBoxPnumPos.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxPnumPos)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.groupBoxPreviewNum = QtWidgets.QGroupBox(self.groupBoxPageNumber)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxPreviewNum.setFont(font)
        self.groupBoxPreviewNum.setObjectName("groupBoxPreviewNum")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBoxPreviewNum)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.lblPreviewNum = QtWidgets.QLabel(self.groupBoxPreviewNum)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lblPreviewNum.setFont(font)
        self.lblPreviewNum.setObjectName("lblPreviewNum")
        self.horizontalLayout_8.addWidget(self.lblPreviewNum)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addWidget(self.groupBoxPreviewNum)
        self.horizontalLayout_7.addWidget(self.groupBoxPageNumber)
        self.groupBoxWatermark = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxWatermark.setFont(font)
        self.groupBoxWatermark.setObjectName("groupBoxWatermark")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBoxWatermark)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.checkBoxEnableWater = QtWidgets.QCheckBox(self.groupBoxWatermark)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxEnableWater.setFont(font)
        self.checkBoxEnableWater.setChecked(False)
        self.checkBoxEnableWater.setObjectName("checkBoxEnableWater")
        self.verticalLayout_5.addWidget(self.checkBoxEnableWater)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.lineEditWaterText = QtWidgets.QLineEdit(self.groupBoxWatermark)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditWaterText.setFont(font)
        self.lineEditWaterText.setObjectName("lineEditWaterText")
        self.verticalLayout_5.addWidget(self.lineEditWaterText)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.groupBoxWaterColor = QtWidgets.QGroupBox(self.groupBoxWatermark)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxWaterColor.setFont(font)
        self.groupBoxWaterColor.setObjectName("groupBoxWaterColor")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBoxWaterColor)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lblWaterColor = QtWidgets.QLabel(self.groupBoxWaterColor)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lblWaterColor.setFont(font)
        self.lblWaterColor.setObjectName("lblWaterColor")
        self.verticalLayout_6.addWidget(self.lblWaterColor)
        self.btnChgWaterColor = QtWidgets.QPushButton(self.groupBoxWaterColor)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnChgWaterColor.setFont(font)
        self.btnChgWaterColor.setObjectName("btnChgWaterColor")
        self.verticalLayout_6.addWidget(self.btnChgWaterColor)
        self.verticalLayout_5.addWidget(self.groupBoxWaterColor)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lblFontSize2 = QtWidgets.QLabel(self.groupBoxWatermark)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblFontSize2.setFont(font)
        self.lblFontSize2.setObjectName("lblFontSize2")
        self.horizontalLayout_13.addWidget(self.lblFontSize2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem11)
        self.spinBoxWaterFontSize = QtWidgets.QSpinBox(self.groupBoxWatermark)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBoxWaterFontSize.setFont(font)
        self.spinBoxWaterFontSize.setMaximum(999)
        self.spinBoxWaterFontSize.setProperty("value", 75)
        self.spinBoxWaterFontSize.setObjectName("spinBoxWaterFontSize")
        self.horizontalLayout_13.addWidget(self.spinBoxWaterFontSize)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lblWaterOpacity = QtWidgets.QLabel(self.groupBoxWatermark)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblWaterOpacity.setFont(font)
        self.lblWaterOpacity.setObjectName("lblWaterOpacity")
        self.horizontalLayout_15.addWidget(self.lblWaterOpacity)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem12)
        self.spinBoxWaterOpacity = QtWidgets.QSpinBox(self.groupBoxWatermark)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBoxWaterOpacity.setFont(font)
        self.spinBoxWaterOpacity.setMaximum(255)
        self.spinBoxWaterOpacity.setProperty("value", 75)
        self.spinBoxWaterOpacity.setObjectName("spinBoxWaterOpacity")
        self.horizontalLayout_15.addWidget(self.spinBoxWaterOpacity)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lblAngle = QtWidgets.QLabel(self.groupBoxWatermark)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblAngle.setFont(font)
        self.lblAngle.setObjectName("lblAngle")
        self.horizontalLayout_14.addWidget(self.lblAngle)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem13)
        self.spinBoxWaterAngle = QtWidgets.QSpinBox(self.groupBoxWatermark)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBoxWaterAngle.setFont(font)
        self.spinBoxWaterAngle.setMaximum(360)
        self.spinBoxWaterAngle.setProperty("value", 20)
        self.spinBoxWaterAngle.setObjectName("spinBoxWaterAngle")
        self.horizontalLayout_14.addWidget(self.spinBoxWaterAngle)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem14)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem15)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem16)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem17)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem18)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem19)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem20)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem21)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem22)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem23)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem24)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem25)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem26)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem27)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem28)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem29)
        self.horizontalLayout_7.addWidget(self.groupBoxWatermark)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBoxCropping = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxCropping.setFont(font)
        self.groupBoxCropping.setObjectName("groupBoxCropping")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxCropping)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem30)
        self.checkBoxEnableCrop = QtWidgets.QCheckBox(self.groupBoxCropping)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxEnableCrop.setFont(font)
        self.checkBoxEnableCrop.setChecked(False)
        self.checkBoxEnableCrop.setObjectName("checkBoxEnableCrop")
        self.verticalLayout.addWidget(self.checkBoxEnableCrop)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblLeft = QtWidgets.QLabel(self.groupBoxCropping)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblLeft.setFont(font)
        self.lblLeft.setObjectName("lblLeft")
        self.horizontalLayout.addWidget(self.lblLeft)
        self.spinBoxLeftMargin = QtWidgets.QSpinBox(self.groupBoxCropping)
        self.spinBoxLeftMargin.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBoxLeftMargin.setFont(font)
        self.spinBoxLeftMargin.setWrapping(False)
        self.spinBoxLeftMargin.setFrame(True)
        self.spinBoxLeftMargin.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBoxLeftMargin.setAccelerated(False)
        self.spinBoxLeftMargin.setMaximum(999999999)
        self.spinBoxLeftMargin.setObjectName("spinBoxLeftMargin")
        self.horizontalLayout.addWidget(self.spinBoxLeftMargin)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblRight = QtWidgets.QLabel(self.groupBoxCropping)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblRight.setFont(font)
        self.lblRight.setObjectName("lblRight")
        self.horizontalLayout_2.addWidget(self.lblRight)
        self.spinBoxRightMargin = QtWidgets.QSpinBox(self.groupBoxCropping)
        self.spinBoxRightMargin.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBoxRightMargin.setFont(font)
        self.spinBoxRightMargin.setMaximum(999999999)
        self.spinBoxRightMargin.setProperty("value", 1920)
        self.spinBoxRightMargin.setObjectName("spinBoxRightMargin")
        self.horizontalLayout_2.addWidget(self.spinBoxRightMargin)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblUp = QtWidgets.QLabel(self.groupBoxCropping)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblUp.setFont(font)
        self.lblUp.setObjectName("lblUp")
        self.horizontalLayout_4.addWidget(self.lblUp)
        self.spinBoxUpMargin = QtWidgets.QSpinBox(self.groupBoxCropping)
        self.spinBoxUpMargin.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBoxUpMargin.setFont(font)
        self.spinBoxUpMargin.setMaximum(999999999)
        self.spinBoxUpMargin.setObjectName("spinBoxUpMargin")
        self.horizontalLayout_4.addWidget(self.spinBoxUpMargin)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblDown = QtWidgets.QLabel(self.groupBoxCropping)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblDown.setFont(font)
        self.lblDown.setObjectName("lblDown")
        self.horizontalLayout_3.addWidget(self.lblDown)
        self.spinBoxDownMargin = QtWidgets.QSpinBox(self.groupBoxCropping)
        self.spinBoxDownMargin.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBoxDownMargin.setFont(font)
        self.spinBoxDownMargin.setMaximum(999999999)
        self.spinBoxDownMargin.setProperty("value", 1080)
        self.spinBoxDownMargin.setObjectName("spinBoxDownMargin")
        self.horizontalLayout_3.addWidget(self.spinBoxDownMargin)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem31, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_12.addWidget(self.groupBoxCropping)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblDpi = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblDpi.setFont(font)
        self.lblDpi.setObjectName("lblDpi")
        self.horizontalLayout_6.addWidget(self.lblDpi)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem32)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.spinBoxDpi = QtWidgets.QSpinBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBoxDpi.setFont(font)
        self.spinBoxDpi.setMaximum(999)
        self.spinBoxDpi.setProperty("value", 100)
        self.spinBoxDpi.setObjectName("spinBoxDpi")
        self.horizontalLayout_5.addWidget(self.spinBoxDpi)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lblFidelity = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblFidelity.setFont(font)
        self.lblFidelity.setObjectName("lblFidelity")
        self.horizontalLayout_12.addWidget(self.lblFidelity)
        self.spinBoxFidelity = QtWidgets.QSpinBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBoxFidelity.setFont(font)
        self.spinBoxFidelity.setMinimum(1)
        self.spinBoxFidelity.setMaximum(100)
        self.spinBoxFidelity.setProperty("value", 95)
        self.spinBoxFidelity.setObjectName("spinBoxFidelity")
        self.horizontalLayout_12.addWidget(self.spinBoxFidelity)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_9.addLayout(self.verticalLayout_10)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem33)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem34)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem35)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem36)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem37)
        self.verticalLayout_12.addWidget(self.groupBox_5)
        spacerItem38 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem38)
        spacerItem39 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem39)
        spacerItem40 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem40)
        spacerItem41 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem41)
        spacerItem42 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem42)
        spacerItem43 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem43)
        spacerItem44 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem44)
        spacerItem45 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem45)
        spacerItem46 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem46)
        spacerItem47 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem47)
        spacerItem48 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem48)
        spacerItem49 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem49)
        spacerItem50 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem50)
        spacerItem51 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem51)
        spacerItem52 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem52)
        spacerItem53 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem53)
        spacerItem54 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem54)
        spacerItem55 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem55)
        spacerItem56 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem56)
        spacerItem57 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem57)
        spacerItem58 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem58)
        self.horizontalLayout_7.addLayout(self.verticalLayout_12)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        spacerItem59 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem59)
        spacerItem60 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem60)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem61 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem61)
        self.btnSavePrefs = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnSavePrefs.setFont(font)
        self.btnSavePrefs.setObjectName("btnSavePrefs")
        self.horizontalLayout_11.addWidget(self.btnSavePrefs)
        spacerItem62 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem62)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        configWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(configWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 942, 21))
        self.menubar.setObjectName("menubar")
        configWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(configWindow)
        self.statusbar.setObjectName("statusbar")
        configWindow.setStatusBar(self.statusbar)

        self.retranslateUi(configWindow)
        QtCore.QMetaObject.connectSlotsByName(configWindow)

    def retranslateUi(self, configWindow):
        _translate = QtCore.QCoreApplication.translate
        configWindow.setWindowTitle(_translate("configWindow", "Pdfize: Configure"))
        self.groupBoxPageNumber.setTitle(_translate("configWindow", "Page number"))
        self.groupBoxNumberingMethod.setTitle(_translate("configWindow", "Numbering method"))
        self.radioFil.setText(_translate("configWindow", "Use file name"))
        self.radioNumb.setText(_translate("configWindow", "Use numbers"))
        self.groupBoxForeColor.setTitle(_translate("configWindow", "Foreground color"))
        self.lblPnumFore.setText(_translate("configWindow", "Preview"))
        self.btnChgPNumFore.setText(_translate("configWindow", "Change..."))
        self.checkBoxPnumAddBG.setText(_translate("configWindow", "Add background"))
        self.groupBoxBckColor.setTitle(_translate("configWindow", "Background color"))
        self.lblPnumBack.setText(_translate("configWindow", "Preview"))
        self.btnChgNumBack.setText(_translate("configWindow", "Change..."))
        self.lblFontSize1.setText(_translate("configWindow", "Font size:"))
        self.lblPosition.setText(_translate("configWindow", "Position:"))
        self.comboBoxPnumPos.setItemText(0, _translate("configWindow", "Bottom right"))
        self.comboBoxPnumPos.setItemText(1, _translate("configWindow", "Top right"))
        self.comboBoxPnumPos.setItemText(2, _translate("configWindow", "Top left"))
        self.comboBoxPnumPos.setItemText(3, _translate("configWindow", "Bottom left"))
        self.groupBoxPreviewNum.setTitle(_translate("configWindow", "Preview"))
        self.lblPreviewNum.setText(_translate("configWindow", "1"))
        self.groupBoxWatermark.setTitle(_translate("configWindow", "Watermark"))
        self.checkBoxEnableWater.setText(_translate("configWindow", "Put watermark"))
        self.lineEditWaterText.setText(_translate("configWindow", "Sample"))
        self.groupBoxWaterColor.setTitle(_translate("configWindow", "Color"))
        self.lblWaterColor.setText(_translate("configWindow", "Preview"))
        self.btnChgWaterColor.setText(_translate("configWindow", "Change..."))
        self.lblFontSize2.setText(_translate("configWindow", "Font size: "))
        self.lblWaterOpacity.setText(_translate("configWindow", "Opacity [0-255]:"))
        self.lblAngle.setText(_translate("configWindow", "Angle [°]:"))
        self.groupBoxCropping.setTitle(_translate("configWindow", "Cropping"))
        self.checkBoxEnableCrop.setText(_translate("configWindow", "Crop images"))
        self.lblLeft.setText(_translate("configWindow", "Left:"))
        self.lblRight.setText(_translate("configWindow", "Right:"))
        self.lblUp.setText(_translate("configWindow", "    Up:"))
        self.lblDown.setText(_translate("configWindow", "Down:"))
        self.groupBox_5.setTitle(_translate("configWindow", "Other"))
        self.lblDpi.setText(_translate("configWindow", "Dpi:"))
        self.lblFidelity.setText(_translate("configWindow", "Fidelity [%]:"))
        self.btnSavePrefs.setText(_translate("configWindow", "Save preferences"))

########################################################################################################################

    def translateTR(self, configureWindow):
        _translate = QtCore.QCoreApplication.translate
        configureWindow.setWindowTitle(_translate("configWindow", "Pdfleştirici: Yapılandır"))
        self.groupBoxPageNumber.setTitle(_translate("configWindow", "Sayfa numarası"))
        self.groupBoxNumberingMethod.setTitle(_translate("configWindow", "Yöntem"))
        self.radioFil.setText(_translate("configWindow", "Dosya adını kullan"))
        self.radioNumb.setText(_translate("configWindow", "Sayı kullan"))
        self.groupBoxForeColor.setTitle(_translate("configWindow", "Ön plan rengi"))
        self.lblPnumFore.setText(_translate("configWindow", "Önizleme"))
        self.btnChgPNumFore.setText(_translate("configWindow", "Değiştir..."))
        self.checkBoxPnumAddBG.setText(_translate("configWindow", "Arkaplan ekle"))
        self.groupBoxBckColor.setTitle(_translate("configWindow", "Arkaplan rengi"))
        self.lblPnumBack.setText(_translate("configWindow", "Önizleme"))
        self.btnChgNumBack.setText(_translate("configWindow", "Değiştir..."))
        self.lblFontSize1.setText(_translate("configWindow", "Punto:"))
        self.lblPosition.setText(_translate("configWindow", "Konum:"))
        self.comboBoxPnumPos.setItemText(0, _translate("configWindow", "Sağ alt"))
        self.comboBoxPnumPos.setItemText(1, _translate("configWindow", "Sağ üst"))
        self.comboBoxPnumPos.setItemText(2, _translate("configWindow", "Sol üst"))
        self.comboBoxPnumPos.setItemText(3, _translate("configWindow", "Sol alt"))
        self.groupBoxPreviewNum.setTitle(_translate("configWindow", "Önizleme"))
        self.lblPreviewNum.setText(_translate("configWindow", "1"))
        self.groupBoxWatermark.setTitle(_translate("configWindow", "Filigran"))
        self.checkBoxEnableWater.setText(_translate("configWindow", "Filigran ekle"))
        self.lineEditWaterText.setText(_translate("configWindow", "Örnek"))
        self.groupBoxWaterColor.setTitle(_translate("configWindow", "Renk"))
        self.lblWaterColor.setText(_translate("configWindow", "Önizleme"))
        self.btnChgWaterColor.setText(_translate("configWindow", "Değiştir..."))
        self.lblFontSize2.setText(_translate("configWindow", "Punto: "))
        self.lblWaterOpacity.setText(_translate("configWindow", "Opaklık [0-255]:"))
        self.lblAngle.setText(_translate("configWindow", "Açı [°]:"))
        self.groupBoxCropping.setTitle(_translate("configWindow", "Kırp"))
        self.checkBoxEnableCrop.setText(_translate("configWindow", "Resimleri kırp"))
        self.lblLeft.setText(_translate("configWindow", "Sol:"))
        self.lblRight.setText(_translate("configWindow", "Sağ:"))
        self.lblUp.setText(_translate("configWindow", "Üst:"))
        self.lblDown.setText(_translate("configWindow", "Alt:"))
        self.groupBox_5.setTitle(_translate("configWindow", "Diğer"))
        self.lblDpi.setText(_translate("configWindow", "Dpi:"))
        self.lblFidelity.setText(_translate("configWindow", "Kalite [%]: "))
        self.btnSavePrefs.setText(_translate("configWindow", "Tercihleri kaydet"))  