# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2 EXCEPT: translateTR() function.
#
# WARNING! All changes made in this file will be lost! If you recompile this file using the "*.ui" file


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(792, 266)
        mainWindow.setStyleSheet("QGroupBox{\n"
"    border: 1px solid rgb(150, 150, 150);\n"
"    margin-top: 0.5em;\n"
"    color: rgb(30, 30, 30);\n"
"}\n"
"QGroupBox::title {\n"
"    background-color: rgb(240, 240, 240);\n"
"    top: -10px;\n"
"    left: 10px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBoxControls = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxControls.sizePolicy().hasHeightForWidth())
        self.groupBoxControls.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBoxControls.setFont(font)
        self.groupBoxControls.setObjectName("groupBoxControls")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBoxControls)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnSelectFolder = QtWidgets.QPushButton(self.groupBoxControls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectFolder.sizePolicy().hasHeightForWidth())
        self.btnSelectFolder.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnSelectFolder.setFont(font)
        self.btnSelectFolder.setObjectName("btnSelectFolder")
        self.horizontalLayout_2.addWidget(self.btnSelectFolder)
        self.lblOr = QtWidgets.QLabel(self.groupBoxControls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblOr.sizePolicy().hasHeightForWidth())
        self.lblOr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblOr.setFont(font)
        self.lblOr.setObjectName("lblOr")
        self.horizontalLayout_2.addWidget(self.lblOr)
        self.btnSelectFiles = QtWidgets.QPushButton(self.groupBoxControls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelectFiles.sizePolicy().hasHeightForWidth())
        self.btnSelectFiles.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnSelectFiles.setFont(font)
        self.btnSelectFiles.setObjectName("btnSelectFiles")
        self.horizontalLayout_2.addWidget(self.btnSelectFiles)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.btnConfigure = QtWidgets.QPushButton(self.groupBoxControls)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnConfigure.sizePolicy().hasHeightForWidth())
        self.btnConfigure.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnConfigure.setFont(font)
        self.btnConfigure.setObjectName("btnConfigure")
        self.verticalLayout_3.addWidget(self.btnConfigure)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.btnPdfize = QtWidgets.QPushButton(self.groupBoxControls)
        self.btnPdfize.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPdfize.sizePolicy().hasHeightForWidth())
        self.btnPdfize.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btnPdfize.setFont(font)
        self.btnPdfize.setObjectName("btnPdfize")
        self.verticalLayout_2.addWidget(self.btnPdfize)
        self.btnOpenOutputFolder = QtWidgets.QPushButton(self.groupBoxControls)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnOpenOutputFolder.setFont(font)
        self.btnOpenOutputFolder.setObjectName("btnOpenOutputFolder")
        self.verticalLayout_2.addWidget(self.btnOpenOutputFolder)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.groupBoxControls)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBoxProcessDetails = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBoxProcessDetails.setFont(font)
        self.groupBoxProcessDetails.setObjectName("groupBoxProcessDetails")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBoxProcessDetails)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.lblRamUsage = QtWidgets.QLabel(self.groupBoxProcessDetails)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblRamUsage.setFont(font)
        self.lblRamUsage.setObjectName("lblRamUsage")
        self.verticalLayout_5.addWidget(self.lblRamUsage)
        self.lblStatus = QtWidgets.QLabel(self.groupBoxProcessDetails)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblStatus.setFont(font)
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout_5.addWidget(self.lblStatus)
        self.lblFileName = QtWidgets.QLabel(self.groupBoxProcessDetails)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblFileName.setFont(font)
        self.lblFileName.setText("")
        self.lblFileName.setObjectName("lblFileName")
        self.verticalLayout_5.addWidget(self.lblFileName)
        self.lblProgress = QtWidgets.QLabel(self.groupBoxProcessDetails)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblProgress.setFont(font)
        self.lblProgress.setText("")
        self.lblProgress.setObjectName("lblProgress")
        self.verticalLayout_5.addWidget(self.lblProgress)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.progressBar = QtWidgets.QProgressBar(self.groupBoxProcessDetails)
        self.progressBar.setProperty("value", 30)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_5.addWidget(self.progressBar)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_4.addWidget(self.groupBoxProcessDetails)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 792, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionSettings = QtWidgets.QAction(mainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionSee_online_help = QtWidgets.QAction(mainWindow)
        self.actionSee_online_help.setObjectName("actionSee_online_help")
        self.actionSee_offline_help = QtWidgets.QAction(mainWindow)
        self.actionSee_offline_help.setObjectName("actionSee_offline_help")
        self.menuMenu.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionSee_online_help)
        self.menuHelp.addAction(self.actionSee_offline_help)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Pdfize"))
        self.groupBoxControls.setTitle(_translate("mainWindow", "Controls"))
        self.btnSelectFolder.setText(_translate("mainWindow", "Select folder"))
        self.lblOr.setText(_translate("mainWindow", "OR"))
        self.btnSelectFiles.setText(_translate("mainWindow", "Select files"))
        self.btnConfigure.setText(_translate("mainWindow", "Configure"))
        self.btnPdfize.setText(_translate("mainWindow", "Pdfize!"))
        self.btnOpenOutputFolder.setText(_translate("mainWindow", "Open output folder"))
        self.groupBoxProcessDetails.setTitle(_translate("mainWindow", "Process details"))
        self.lblRamUsage.setText(_translate("mainWindow", " "))
        self.lblStatus.setText(_translate("mainWindow", "Status: Default input folder selected"))
        self.menuMenu.setTitle(_translate("mainWindow", "Menu"))
        self.menuHelp.setTitle(_translate("mainWindow", "Help"))
        self.actionSettings.setText(_translate("mainWindow", "App settings"))
        self.actionSee_online_help.setText(_translate("mainWindow", "See online help"))
        self.actionSee_offline_help.setText(_translate("mainWindow", "See offline help"))

#####################################################################################################################################

    def translateTR(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Pdfleştirici"))
        self.groupBoxControls.setTitle(_translate("mainWindow", "Kontroller"))
        self.btnSelectFolder.setText(_translate("mainWindow", "Klasör seç"))
        self.lblOr.setText(_translate("mainWindow", "YA DA"))
        self.btnSelectFiles.setText(_translate("mainWindow", "Dosya seç"))
        self.btnConfigure.setText(_translate("mainWindow", "Yapılandır"))
        self.btnPdfize.setText(_translate("mainWindow", "Pdfleştir!"))
        self.btnOpenOutputFolder.setText(_translate("mainWindow", "Çıktı dizinini aç"))
        self.groupBoxProcessDetails.setTitle(_translate("mainWindow", "İşlem detayları"))
        self.lblRamUsage.setText(_translate("mainWindow", " "))
        self.lblStatus.setText(_translate("mainWindow", "Durum: Varsayılan girdi klasörü seçildi"))
        self.lblFileName.setText(_translate("mainWindow", ""))
        self.lblProgress.setText(_translate("mainWindow", ""))
        self.menuMenu.setTitle(_translate("mainWindow", "Menü"))
        self.menuHelp.setTitle(_translate("mainWindow", "Yardım"))
        self.actionSettings.setText(_translate("mainWindow", "Uygulama Ayarları"))
        self.actionSee_online_help.setText(_translate("mainWindow", "Çevrimiçi yardımı aç"))
        self.actionSee_offline_help.setText(_translate("mainWindow", "Çevrimdışı yardımı aç"))